### ISSUE TITLE
UseCase Diagram für Benutzerverwaltung (Nguyen, Thürling)

### ISSUE THREAD

**Issue by paul-tat** [paul-tat/tgbbz1Base#15]
Ein Use Case Diagramm welches den Entwicklern eine Übersicht über die gewünschten Funktionen gibt

**Comment by M123th** [comment]
[Grünkohl.pdf](https://github.com/paul-tat/tgbbz1Base/files/8047405/Grunkohl.pdf)

**Comment by M123th** [comment]
[Grünkohl.pdf](https://github.com/paul-tat/tgbbz1Base/files/8222080/Grunkohl.pdf)
verbesserte Version
